server/idong_site/idong/urls.py
from django.conf.urls import patterns, include, url
from rest_framework.urlpatterns import format_suffix_patterns
from idong import views, images
from idong.models import Party

from django.views.generic import DetailView, ListView

urlpatterns = patterns('',
    url(r'^users/$', views.UserList.as_view()),
    url(r'^users/(?P<pk>[0-9]+)/$', views.UserDetail.as_view(), name='user_detail'),
    url(r'^parties/$', views.PartyList.as_view()),
    url(r'^parties/(?P<pk>\d+)/$', views.PartyDetail.as_view()),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    #url(r'^select$', images.select),
    url(r'^upload$', images.upload),
    url(r'^adduserimg/$', views.UserImages.as_view()),
    url(r'^userimg/user=(?P<user>[0-9]+)/$', views.UserImages.as_view()),
    url(r'^partyimg/party=(?P<party>[0-9]+)/$', views.PartyImages.as_view()),
    url(r'^addpartyimg/$', views.PartyImages.as_view()),

    url(r'^web-parties/$',
        ListView.as_view(
            model=Party,
            context_object_name='all_parties',
            template_name='idong/index.html'),
        name='web_list'),
    url(r'^web-detail/(?P<pk>\d+)/$',
        DetailView.as_view(
            model=Party,
            template_name='idong/detail.html'),
        name='web_detail'),
    #url(r'^web/$', include('idong.web_urls', namespace='web')),
    #url(r'^web/$', views.PartyList.as_view()),
)

urlpatterns = format_suffix_patterns(urlpatterns)

server/idong_site/mysite/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^mysite/', include('mysite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    #url(r'contact/', include('contact.urls')),
    url(r'', include('idong.urls', namespace='idong')),
)

server/idong_site/rest_framework/runtests/urls.py
"""
Blank URLConf just to keep runtests.py happy.
"""
from rest_framework.compat import patterns

urlpatterns = patterns('',
)

server/idong_site/rest_framework/urls.py
"""
Login and logout views for the browsable API.

Add these to your root URLconf if you're using the browsable API and
your API requires authentication.

The urls must be namespaced as 'rest_framework', and you should make sure
your authentication settings include `SessionAuthentication`.

    urlpatterns = patterns('',
        ...
        url(r'^auth', include('rest_framework.urls', namespace='rest_framework'))
    )
"""
from __future__ import unicode_literals
from rest_framework.compat import patterns, url


template_name = {'template_name': 'rest_framework/login.html'}

urlpatterns = patterns('django.contrib.auth.views',
    url(r'^login/$', 'login', template_name, name='login'),
    url(r'^logout/$', 'logout', template_name, name='logout'),
)

server/idong_site/idong/models.py
from django.db import models

# Currently, just list all sports here
# Maybe it'd better be stored in table,
# and related to user's interest
SPORT_CHOICES=(
    ('0', 'Basketball'),
    ('1', 'Footbal'),
    ('2', 'Tennis'),
    ('3', 'Biking'),
)


# specify orignal pic or thumbs
IMAGE_TYPE=(
    ('0', '0'),   # orignal pic
    ('1', '128'), # 128 X 128 thumb
    ('2', '256'), # 256 X 256 thumb
)
class Party(models.Model):
    initiator_user = models.ForeignKey('auth.User', related_name='parties')
    title       = models.CharField(max_length='50', blank=True)
    #category    = models.PositiveSmallIntegerField(blank=True)
    # TODO: related to PartyType
    category    = models.CharField(choices=SPORT_CHOICES,
                                    default='Basketball',
                                    max_length=100)
    start_time  = models.DateTimeField(auto_now_add=True)
    end_time    = models.DateTimeField()
    description = models.TextField(max_length='500', blank=True)
    # TODO: stadium
    location    = models.CharField(max_length='100', blank=True)
    #TODO
    image_urls  = models.CharField(max_length='4000', blank=True)

    #user_party  = models.ManyToManyField(User, related_name='user_party', through='UserParty')
    participants = models.ManyToManyField('auth.User', related_name='attended_parties')
    likers = models.ManyToManyField('auth.User', related_name='liked_parties')

    class Meta:
        ordering = [ '-start_time' ]

    def get_participants_num(self):
        return self.participants.count()

    def get_likers_num(self):
        return self.likers.count()

    def get_thumbnail(self):
        return self.image_urls.split(',')[0]


SEX_CHOICES=(('female', 'Female'), ('male', 'Male'), ('secret', 'Secret'))

class UserInfo:
    import datetime

    uid = models.OneToOneField('auth.User', primary_key=True)
    username = models.CharField(max_length='40')
    nickname = models.CharField(max_length='40', blank=True)
    email = models.EmailField()
    sex = models.CharField(choices=SEX_CHOICES, default='Female')
    phone_num = models.CharField(max_length='20')
    birthday = models.DateField(default=datetime.date(1985, 1, 1))
    qq = models.CharField(max_length='20')
    weibo = models.CharField(max_length='40')
    # TODO: What relationship to PartyType?
    #interests = models.ForeignKey(PartyType)
    address = models.TextField(max_length='200')
    company = models.CharField(max_length='200')
    school = models.CharField(max_length='200')
    # TODO: What purpose?
    major = models.CharField(max_length='200')
    # TODO
    image_urls = models.CharField(max_length='4000', blank=True)

    class Meta():
        ordering = ('username')

class PartyType:
    name = models.CharField(max_length='20')
    description = models.TextField(max_length='400')
    calorie_per_hour = models.PositiveSmallIntegerField()

class UserImages:
    user = models.ForeignKey('auth.User', related_name='user_images')
    url  = models.CharField(max_length=4000 )

class PartyImages:
    party = models.ForeignKey(Party, related_name='party_images')
    url   = models.CharField(max_length=4000)

class UserImages(models.Model):
    user = models.ForeignKey('auth.User', related_name='user_images')
    date = models.DateTimeField(auto_now_add = True)
    title  = models.CharField(max_length=100)
    image  = models.CharField(max_length=4000 )
    imgtype = models.CharField(max_length=2)


class PartyImages(models.Model):
    party = models.ForeignKey(Party, related_name='party_images')
    date = models.DateTimeField(auto_now_add = True)
    title  = models.CharField(max_length=100)
    image  = models.CharField(max_length=4000 )
    imgtype = models.CharField(max_length=2)

server/idong_site/idong/views.py
from idong.models import Party, UserImages, PartyImages
from idong.serializers import UserSerializer, PartyBriefSerializer, PartyDetailSerializer, UserImagesSerializer, PartyImagesSerializer
from rest_framework import generics
from django.contrib.auth.models import User
from rest_framework import permissions
from django.http import HttpResponse

class UserList(generics.ListAPIView):
    model = User
    serializer_class = UserSerializer

class UserDetail(generics.RetrieveAPIView):
    model = User
    serializer_class = UserSerializer


class PartyList(generics.ListAPIView):
    model = Party
    serializer_class = PartyBriefSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

class PartyDetail(generics.RetrieveUpdateDestroyAPIView):
    model = Party
    serializer_class = PartyDetailSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

class UserImages(generics.ListAPIView):
    model = UserImages
    serializer_class = UserImagesSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

class PartyImages(generics.ListAPIView):
    model = PartyImages
    serializer_class = PartyImagesSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

server/idong_site/idong/templates/idong/base.html
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="http://img3.douban.com/css/loc/packed_base4832867365.css">
    <link href="http://img3.douban.com/css/packed_douban9859329871.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="http://img3.douban.com/misc/mixed_static/5a90e0d916dc20a4.css">
    <title>{% block title %}My amazing site{% endblock %}</title>
</head>
<body>
<h1>Hello, world</h1>

{% load url from future %}
{% block content %}

<div class="article">
  
  <ul class="events-list events-list-pic100 events-list-psmall">
      <li class="list-entry" itemscope="" itemtype="http://data-vocabulary.org/Event">
      <div class="pic">
        <a href="http://www.douban.com/event/18681059/">
          <img data-lazy="http://img3.douban.com/pview/event_poster/median/public/fd4c304edc0b868.jpg" src="http://img3.douban.com/pview/event_poster/median/public/fd4c304edc0b868.jpg" width="110" itemprop="photo">
        </a>
      </div>
      <div class="info">
        <div class="title">
          <a href="http://www.douban.com/event/18681059/" title="Travis、张悬、Lenka、彭坦领衔 上海草莓音乐节 门票免费抢！！" itemprop="url">
            <span itemprop="summary">Travis、张悬、Lenka、彭坦领衔 上海草莓音乐节 门票免费抢！！</span>
          </a>
        </div>
        
          <p class="event-cate-tag">
            <a href="http://www.douban.com/event/search?loc=shanghai&amp;search_text=%E9%9F%B3%E4%B9%90%E8%8A%82&amp;p=week">音乐节</a>&nbsp;
            <a href="http://www.douban.com/event/search?loc=shanghai&amp;search_text=%E8%8D%89%E8%8E%93%E9%9F%B3%E4%B9%90%E8%8A%82&amp;p=week">草莓音乐节</a>&nbsp;
            <a href="http://www.douban.com/event/search?loc=shanghai&amp;search_text=%E6%91%87%E6%BB%9A&amp;p=week">摇滚</a>&nbsp;
          </p>
        <ul>
          <li class="event-time">
            <span>时间：</span>
            
            04月18日 ~ 04月27日 每天14:00-14:30 
            <time itemprop="startDate" datetime="2013-04-18T14:00:00"></time>
            <time itemprop="endDate" datetime="2013-04-27T14:30:00"></time>
          </li>
          <li title="上海 浦东新区 世博公园">
            <span>地点：</span>
              浦东新区
            世博公园
             <meta itemscope="" itemprop="location" content="上海 浦东新区 世博公园">
          </li>
          <li class="fee">
            
              <span>费用：</span>
              <strong>免费</strong>
          </li>
          <li>
            <span>发起：</span>
            <a target="db-event-owner" href="http://site.douban.com/chinaticket/">中票在线</a>
          </li>
        </ul>
        <p class="counts">
            <span>486人参加</span> <span class="pipe"></span> <span>118人感兴趣</span>
        </p>
      </div>
      </li>
      <li class="list-entry" itemscope="" itemtype="http://data-vocabulary.org/Event">
      <div class="pic">
        <a href="http://www.douban.com/event/18419138/">
          <img data-lazy="http://img3.douban.com/pview/event_poster/median/public/66e2b48ce1087d8.jpg" src="http://img3.douban.com/pview/event_poster/median/public/66e2b48ce1087d8.jpg" width="110" itemprop="photo">
        </a>
      </div>
      <div class="info">
        <div class="title">
          <a href="http://www.douban.com/event/18419138/" title="【新知推荐】老舍原著改编 独角戏《我这一辈子》" itemprop="url">
            <span itemprop="summary">【新知推荐】老舍原著改编 独角戏《我这一辈子》</span>
          </a>
        </div>
        
        <ul>
          <li class="event-time">
            <span>时间：</span>
            
            04月27日 周六 19:30-21:30 ...
            <time itemprop="startDate" datetime="2013-04-27T19:30:00"></time>
            <time itemprop="endDate" datetime="2013-04-28T21:30:00"></time>
          </li>
          <li title="上海 长宁区 兰心大戏院">
            <span>地点：</span>
              长宁区
            兰心大戏院
             <meta itemscope="" itemprop="location" content="上海 长宁区 兰心大戏院">
               
               <span itemprop="geo" itemscope="" itemtype="http://data-vocabulary.org/​Geo">
                  <meta itemprop="latitude" content="31.220366">
                  <meta itemprop="longitude" content="121.424622">
               </span>
          </li>
          <li class="fee">
            
              <span>费用：</span>
              <strong>280元 / 180元 / 100元</strong>
          </li>
          <li>
            <span>发起：</span>
            <a target="db-event-owner" href="http://site.douban.com/sixiangshi/">国学新知</a>
          </li>
        </ul>
        <p class="counts">
            <span>56人参加</span> <span class="pipe"></span> <span>239人感兴趣</span>
        </p>
      </div>
      </li>
  </ul>

</div>

{% endblock %}

</body>
</html>

server/idong_site/idong/templates/idong/index.html
{% extends "idong/base.html" %}

{% load url from future %}

{% block title %}
iDong(Holy) --- List all parties
{% endblock %}


{% block content %}
<div class="article">
  
  <ul class="events-list events-list-pic100 events-list-psmall">

    {% for party in all_parties %}
      <li class="list-entry" itemscope="" itemtype="http://data-vocabulary.org/Event">
      <div class="pic">
        <a href="{% url 'idong:web_detail' party.id %}">
          <img data-lazy="{{ party.image_urls }}" src="{{ party.image_urls }}" width="110" itemprop="photo">
        </a>
      </div>
      <div class="info">
        <div class="title">
          <a href="{% url 'idong:web_detail' party.id %}" title="{{ party.title }}" itemprop="url">
            <span itemprop="summary">{{ party.title }}</span>
          </a>
        </div>
        
          <p class="event-cate-tag">
            <a href="http://www.douban.com/event/search?loc=shanghai&amp;search_text=%E9%9F%B3%E4%B9%90%E8%8A%82&amp;p=week">{{ party.category }}</a>
        <ul>
          <li class="event-time">
            <span>时间：</span>
            
            {{ party.start_time }} ~ {{ party.end_time }}
            <!--TODO: What effect do the following two fields make?-->
            <time itemprop="startDate" datetime="2013-04-18T14:00:00"></time>
            <time itemprop="endDate" datetime="2013-04-27T14:30:00"></time>
          </li>
          <li title="{{ party.location }}">
            <span>地点：</span>
              {{ party.location }}
             <meta itemscope="" itemprop="location" content="{{ party.location }}">
          </li>
          <li class="fee">
            
              <span>费用：</span>
              <strong>免费</strong>
          </li>
          <li>
            <span>发起：</span>
            <a target="db-event-owner" href="{% url 'idong:user_detail' party.initiator_user.id %}">{{ party.initiator_user }}</a>
          </li>
        </ul>
        <p class="counts">
            <span>{{ party.participants.all.count }}人参加</span> <span class="pipe"></span> <span>{{ party.likers.all.count }}人感兴趣</span>
        </p>
      </div>
      </li>

    {% endfor %}




      <li class="list-entry" itemscope="" itemtype="http://data-vocabulary.org/Event">
      <div class="pic">
        <a href="http://www.douban.com/event/18681059/">
          <img data-lazy="http://img3.douban.com/pview/event_poster/median/public/fd4c304edc0b868.jpg" src="http://img3.douban.com/pview/event_poster/median/public/fd4c304edc0b868.jpg" width="110" itemprop="photo">
        </a>
      </div>
      <div class="info">
        <div class="title">
          <a href="http://www.douban.com/event/18681059/" title="Travis、张悬、Lenka、彭坦领衔 上海草莓音乐节 门票免费抢！！" itemprop="url">
            <span itemprop="summary">Travis、张悬、Lenka、彭坦领衔 上海草莓音乐节 门票免费抢！！</span>
          </a>
        </div>
        
          <p class="event-cate-tag">
            <a href="http://www.douban.com/event/search?loc=shanghai&amp;search_text=%E9%9F%B3%E4%B9%90%E8%8A%82&amp;p=week">音乐节</a>&nbsp;
            <a href="http://www.douban.com/event/search?loc=shanghai&amp;search_text=%E8%8D%89%E8%8E%93%E9%9F%B3%E4%B9%90%E8%8A%82&amp;p=week">草莓音乐节</a>&nbsp;
            <a href="http://www.douban.com/event/search?loc=shanghai&amp;search_text=%E6%91%87%E6%BB%9A&amp;p=week">摇滚</a>&nbsp;
          </p>
        <ul>
          <li class="event-time">
            <span>时间：</span>
            
            04月18日 ~ 04月27日 每天14:00-14:30 
            <time itemprop="startDate" datetime="2013-04-18T14:00:00"></time>
            <time itemprop="endDate" datetime="2013-04-27T14:30:00"></time>
          </li>
          <li title="上海 浦东新区 世博公园">
            <span>地点：</span>
              浦东新区
            世博公园
             <meta itemscope="" itemprop="location" content="上海 浦东新区 世博公园">
          </li>
          <li class="fee">
            
              <span>费用：</span>
              <strong>免费</strong>
          </li>
          <li>
            <span>发起：</span>
            <a target="db-event-owner" href="http://site.douban.com/chinaticket/">中票在线</a>
          </li>
        </ul>
        <p class="counts">
            <span>486人参加</span> <span class="pipe"></span> <span>118人感兴趣</span>
        </p>
      </div>
      </li>
  </ul>

</div>
{% endblock %}